[build]
  base = ""
  command = "npm run build"
  publish = "client/dist"

[[headers]]
  # Apply these headers to all paths
  for = "/*"
  [headers.values]
    # Cache control for service worker file (if you have one)
    "Cache-Control" = "no-cache"

[[headers]]
  # Apply these headers to static assets
  for = "/assets/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  # Apply these headers to other static files
  for = "/*.(js|css|jpg|jpeg|png|gif|svg|ico|eot|ttf|woff|woff2|otf)"
  [headers.values]
    "Cache-Control" = "public, max-age=604800"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  